"""create tables

Revision ID: 0905fc78f930
Revises: 892bb7f96466
Create Date: 2026-03-04 11:30:41.616699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0905fc78f930'
down_revision = '892bb7f96466'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('opens_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closes_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('data_hash', sa.String(length=255), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elections_data_hash'), 'elections', ['data_hash'], unique=False)
    op.create_index(op.f('ix_elections_id'), 'elections', ['id'], unique=False)
    op.create_index(op.f('ix_elections_status'), 'elections', ['status'], unique=False)
    op.create_table('election_voter_roll',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('election_id', sa.Uuid(), nullable=False),
    sa.Column('electorate_id', sa.Uuid(), nullable=False),
    sa.Column('has_voted', sa.Boolean(), nullable=False),
    sa.Column('voted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('added_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['electorate_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'electorate_id', name='uq_voter_roll_entry')
    )
    op.create_index(op.f('ix_election_voter_roll_election_id'), 'election_voter_roll', ['election_id'], unique=False)
    op.create_index(op.f('ix_election_voter_roll_electorate_id'), 'election_voter_roll', ['electorate_id'], unique=False)
    op.create_index(op.f('ix_election_voter_roll_has_voted'), 'election_voter_roll', ['has_voted'], unique=False)
    op.create_index(op.f('ix_election_voter_roll_id'), 'election_voter_roll', ['id'], unique=False)
    op.add_column('audit_logs', sa.Column('election_id', sa.Uuid(), nullable=True))
    op.create_index('ix_audit_election', 'audit_logs', ['election_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_election_id'), 'audit_logs', ['election_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'elections', ['election_id'], ['id'], ondelete='RESTRICT')
    op.drop_constraint(op.f('candidates_portfolio_id_fkey'), 'candidates', type_='foreignkey')
    op.create_foreign_key(None, 'candidates', 'portfolios', ['portfolio_id'], ['id'], ondelete='RESTRICT')
    op.add_column('portfolios', sa.Column('election_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=False)
    op.create_index(op.f('ix_portfolios_election_id'), 'portfolios', ['election_id'], unique=False)
    op.create_unique_constraint('uq_portfolio_per_election', 'portfolios', ['election_id', 'name'])
    op.create_foreign_key(None, 'portfolios', 'elections', ['election_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('students', 'voting_pin_hash',
               existing_type=sa.VARCHAR(length=1550),
               type_=sa.String(length=512),
               nullable=True)
    op.create_index(op.f('ix_students_is_deleted'), 'students', ['is_deleted'], unique=False)
    op.add_column('votes', sa.Column('election_id', sa.Uuid(), nullable=False))
    op.add_column('votes', sa.Column('voting_token_id', sa.Uuid(), nullable=False))
    op.drop_index(op.f('ix_votes_electorate_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_electorate_valid'), table_name='votes')
    op.drop_constraint(op.f('uq_vote_electorate_portfolio'), 'votes', type_='unique')
    op.create_index('ix_votes_candidate_valid', 'votes', ['candidate_id', 'is_valid'], unique=False)
    op.create_index('ix_votes_election', 'votes', ['election_id'], unique=False)
    op.create_index(op.f('ix_votes_election_id'), 'votes', ['election_id'], unique=False)
    op.create_index('ix_votes_token', 'votes', ['voting_token_id'], unique=False)
    op.create_index(op.f('ix_votes_voting_token_id'), 'votes', ['voting_token_id'], unique=False)
    op.create_unique_constraint('uq_vote_token_portfolio', 'votes', ['voting_token_id', 'portfolio_id'])
    op.drop_constraint(op.f('votes_candidate_id_fkey'), 'votes', type_='foreignkey')
    op.drop_constraint(op.f('votes_voting_session_id_fkey'), 'votes', type_='foreignkey')
    op.drop_constraint(op.f('votes_portfolio_id_fkey'), 'votes', type_='foreignkey')
    op.drop_constraint(op.f('votes_electorate_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'candidates', ['candidate_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'votes', 'portfolios', ['portfolio_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'votes', 'elections', ['election_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'votes', 'voting_sessions', ['voting_session_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'votes', 'voting_tokens', ['voting_token_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('votes', 'electorate_id')
    op.add_column('voting_sessions', sa.Column('election_id', sa.Uuid(), nullable=False))
    op.add_column('voting_sessions', sa.Column('voting_token_id', sa.Uuid(), nullable=False))
    op.add_column('voting_sessions', sa.Column('station_identifier', sa.String(length=255), nullable=True))
    op.add_column('voting_sessions', sa.Column('vote_submitted', sa.Boolean(), nullable=False))
    op.alter_column('voting_sessions', 'electorate_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_voting_sessions_device_fingerprint'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_user_agent_hash'), table_name='voting_sessions')
    op.create_index(op.f('ix_voting_sessions_election_id'), 'voting_sessions', ['election_id'], unique=False)
    op.create_index(op.f('ix_voting_sessions_station_identifier'), 'voting_sessions', ['station_identifier'], unique=False)
    op.create_index(op.f('ix_voting_sessions_voting_token_id'), 'voting_sessions', ['voting_token_id'], unique=False)
    op.create_foreign_key(None, 'voting_sessions', 'voting_tokens', ['voting_token_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'voting_sessions', 'elections', ['election_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('voting_sessions', 'device_fingerprint')
    op.drop_column('voting_sessions', 'user_agent_hash')
    op.add_column('voting_tokens', sa.Column('election_id', sa.Uuid(), nullable=False))
    op.add_column('voting_tokens', sa.Column('is_used', sa.Boolean(), nullable=False))
    op.add_column('voting_tokens', sa.Column('used_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('voting_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=1550),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.create_index(op.f('ix_voting_tokens_election_id'), 'voting_tokens', ['election_id'], unique=False)
    op.create_unique_constraint('uq_token_per_election_voter', 'voting_tokens', ['election_id', 'electorate_id'])
    op.create_foreign_key(None, 'voting_tokens', 'elections', ['election_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voting_tokens', type_='foreignkey')
    op.drop_constraint('uq_token_per_election_voter', 'voting_tokens', type_='unique')
    op.drop_index(op.f('ix_voting_tokens_election_id'), table_name='voting_tokens')
    op.alter_column('voting_tokens', 'token_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=1550),
               existing_nullable=False)
    op.drop_column('voting_tokens', 'used_at')
    op.drop_column('voting_tokens', 'is_used')
    op.drop_column('voting_tokens', 'election_id')
    op.add_column('voting_sessions', sa.Column('user_agent_hash', sa.VARCHAR(length=1550), autoincrement=False, nullable=True))
    op.add_column('voting_sessions', sa.Column('device_fingerprint', sa.VARCHAR(length=1550), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'voting_sessions', type_='foreignkey')
    op.drop_constraint(None, 'voting_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_voting_sessions_voting_token_id'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_station_identifier'), table_name='voting_sessions')
    op.drop_index(op.f('ix_voting_sessions_election_id'), table_name='voting_sessions')
    op.create_index(op.f('ix_voting_sessions_user_agent_hash'), 'voting_sessions', ['user_agent_hash'], unique=False)
    op.create_index(op.f('ix_voting_sessions_device_fingerprint'), 'voting_sessions', ['device_fingerprint'], unique=False)
    op.alter_column('voting_sessions', 'electorate_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('voting_sessions', 'vote_submitted')
    op.drop_column('voting_sessions', 'station_identifier')
    op.drop_column('voting_sessions', 'voting_token_id')
    op.drop_column('voting_sessions', 'election_id')
    op.add_column('votes', sa.Column('electorate_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_electorate_id_fkey'), 'votes', 'students', ['electorate_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('votes_portfolio_id_fkey'), 'votes', 'portfolios', ['portfolio_id'], ['id'])
    op.create_foreign_key(op.f('votes_voting_session_id_fkey'), 'votes', 'voting_sessions', ['voting_session_id'], ['id'])
    op.create_foreign_key(op.f('votes_candidate_id_fkey'), 'votes', 'candidates', ['candidate_id'], ['id'])
    op.drop_constraint('uq_vote_token_portfolio', 'votes', type_='unique')
    op.drop_index(op.f('ix_votes_voting_token_id'), table_name='votes')
    op.drop_index('ix_votes_token', table_name='votes')
    op.drop_index(op.f('ix_votes_election_id'), table_name='votes')
    op.drop_index('ix_votes_election', table_name='votes')
    op.drop_index('ix_votes_candidate_valid', table_name='votes')
    op.create_unique_constraint(op.f('uq_vote_electorate_portfolio'), 'votes', ['electorate_id', 'portfolio_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_votes_electorate_valid'), 'votes', ['electorate_id', 'is_valid'], unique=False)
    op.create_index(op.f('ix_votes_electorate_id'), 'votes', ['electorate_id'], unique=False)
    op.drop_column('votes', 'voting_token_id')
    op.drop_column('votes', 'election_id')
    op.drop_index(op.f('ix_students_is_deleted'), table_name='students')
    op.alter_column('students', 'voting_pin_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=1550),
               nullable=False)
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_constraint('uq_portfolio_per_election', 'portfolios', type_='unique')
    op.drop_index(op.f('ix_portfolios_election_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=True)
    op.drop_column('portfolios', 'election_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.create_foreign_key(op.f('candidates_portfolio_id_fkey'), 'candidates', 'portfolios', ['portfolio_id'], ['id'])
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_election_id'), table_name='audit_logs')
    op.drop_index('ix_audit_election', table_name='audit_logs')
    op.drop_column('audit_logs', 'election_id')
    op.drop_index(op.f('ix_election_voter_roll_id'), table_name='election_voter_roll')
    op.drop_index(op.f('ix_election_voter_roll_has_voted'), table_name='election_voter_roll')
    op.drop_index(op.f('ix_election_voter_roll_electorate_id'), table_name='election_voter_roll')
    op.drop_index(op.f('ix_election_voter_roll_election_id'), table_name='election_voter_roll')
    op.drop_table('election_voter_roll')
    op.drop_index(op.f('ix_elections_status'), table_name='elections')
    op.drop_index(op.f('ix_elections_id'), table_name='elections')
    op.drop_index(op.f('ix_elections_data_hash'), table_name='elections')
    op.drop_table('elections')
    # ### end Alembic commands ###
