"""cascade voting sessions

Revision ID: 406f04d7cbf5
Revises: d16aee9bfc6a
Create Date: 2026-02-10 23:52:09.165670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406f04d7cbf5'
down_revision = 'd16aee9bfc6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('voting_sessions_electorate_id_fkey'), 'voting_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'voting_sessions', 'students', ['electorate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voting_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('voting_sessions_electorate_id_fkey'), 'voting_sessions', 'students', ['electorate_id'], ['id'])
    # ### end Alembic commands ###
