"""add logo columns to elections

Revision ID: 45f644efdf55
Revises: c716aff91b22
Create Date: 2026-03-05 23:43:55.527314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f644efdf55'
down_revision = 'c716aff91b22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
