"""cascade voting sessions

Revision ID: 4f583ea72ab3
Revises: 406f04d7cbf5
Create Date: 2026-02-11 00:09:38.929562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f583ea72ab3'
down_revision = '406f04d7cbf5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('votes_electorate_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'students', ['electorate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_electorate_id_fkey'), 'votes', 'students', ['electorate_id'], ['id'])
    # ### end Alembic commands ###
