"""add_name_to_students

Revision ID: 5af92da6ada1
Revises: 20260218_add_vote_type
Create Date: 2026-02-21 02:48:48.759687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af92da6ada1'
down_revision = '20260218_add_vote_type'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_column('students', 'name')
    # ### end Alembic commands ###
