"""Add cascade delete to voting tokens and device registrations

Revision ID: 67703bb0fe1c
Revises: 4f583ea72ab3
Create Date: 2026-02-11 01:07:51.215607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67703bb0fe1c'
down_revision = '4f583ea72ab3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_registrations', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.add_column('device_registrations', sa.Column('verification_attempts', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('device_registrations_electorate_id_fkey'), 'device_registrations', type_='foreignkey')
    op.create_foreign_key(None, 'device_registrations', 'students', ['electorate_id'], ['id'], ondelete='CASCADE')
    op.drop_column('device_registrations', 'ban_count')
    op.drop_column('device_registrations', 'is_banned')
    op.drop_column('device_registrations', 'ban_reason')
    op.drop_constraint(op.f('voting_tokens_electorate_id_fkey'), 'voting_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'voting_tokens', 'students', ['electorate_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voting_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('voting_tokens_electorate_id_fkey'), 'voting_tokens', 'students', ['electorate_id'], ['id'])
    op.add_column('device_registrations', sa.Column('ban_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('device_registrations', sa.Column('is_banned', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('device_registrations', sa.Column('ban_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'device_registrations', type_='foreignkey')
    op.create_foreign_key(op.f('device_registrations_electorate_id_fkey'), 'device_registrations', 'students', ['electorate_id'], ['id'])
    op.drop_column('device_registrations', 'verification_attempts')
    op.drop_column('device_registrations', 'is_verified')
    # ### end Alembic commands ###
