"""test1

Revision ID: 892bb7f96466
Revises: 5af92da6ada1
Create Date: 2026-02-26 23:55:12.780492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892bb7f96466'
down_revision = '5af92da6ada1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('actor_role', sa.String(length=50), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_event_type', 'audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index('ix_votes_electorate_valid', 'votes', ['electorate_id', 'is_valid'], unique=False)
    op.create_index('ix_votes_portfolio_valid', 'votes', ['portfolio_id', 'is_valid'], unique=False)
    op.create_unique_constraint('uq_vote_electorate_portfolio', 'votes', ['electorate_id', 'portfolio_id'])
    op.add_column('voting_tokens', sa.Column('failure_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voting_tokens', 'failure_count')
    op.drop_constraint('uq_vote_electorate_portfolio', 'votes', type_='unique')
    op.drop_index('ix_votes_portfolio_valid', table_name='votes')
    op.drop_index('ix_votes_electorate_valid', table_name='votes')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('ix_audit_event_type', table_name='audit_logs')
    op.drop_index('ix_audit_created', table_name='audit_logs')
    op.drop_index('ix_audit_actor', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
