"""create tables

Revision ID: c716aff91b22
Revises: 0905fc78f930
Create Date: 2026-03-05 23:39:37.251591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c716aff91b22'
down_revision = '0905fc78f930'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elections', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('elections', sa.Column('logo_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elections', 'logo_filename')
    op.drop_column('elections', 'logo_url')
    # ### end Alembic commands ###
