"""update schema

Revision ID: d16aee9bfc6a
Revises: f8775df606b2
Create Date: 2026-02-10 23:44:02.970103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd16aee9bfc6a'
down_revision = 'f8775df606b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voting_sessions', 'electorate_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voting_sessions', 'electorate_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
