"""message

Revision ID: e9cea6b2dce3
Revises: 892bb7f96466
Create Date: 2026-03-07 07:02:43.061153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9cea6b2dce3'
down_revision = '892bb7f96466'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('logo_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elections_id'), 'elections', ['id'], unique=False)
    op.create_index(op.f('ix_elections_name'), 'elections', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_elections_name'), table_name='elections')
    op.drop_index(op.f('ix_elections_id'), table_name='elections')
    op.drop_table('elections')
    # ### end Alembic commands ###
